Web/SummaryReports/Models/ErrorViewModel.cs
namespace Report.WebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/SummaryReports/Models/SharedSettings.cs
namespace Report.WebUI.Models
{
    public static class SharedSettings
    {
        public const string ByVersion = "ByVersion";
        public const string ByTimeline = "ByTimelines";
        public static string Setting { get; set; }
        public static string Version { get; set; }

        public static bool IsPresent => Version != null && Setting == ByVersion || Setting == ByTimeline;
    }
}

Web/SummaryReports/Models/SummaryReportDataPoint.cs
using System.Runtime.Serialization;

namespace Report.WebUI.Models
{
    [DataContract]
    public class SummaryReportDataPoint
    {
        public SummaryReportDataPoint(string version, int samples, int failCases, double average, double percentile90th, double percentile95th, double percentile99th, double throughPut)
        {
            Version = version;
            Samples = samples;
            FailCases = failCases;
            Average = average;
            Percentile90th = percentile90th;
            Percentile95th = percentile95th;
            Percentile99th = percentile99th;
            Throughput = throughPut;
        }

        [DataMember(Name = "version")]
        public string Version;

        [DataMember(Name = "samples")]
        public int? Samples = null;

        [DataMember(Name = "failCases")]
        public int? FailCases = null;

        [DataMember(Name = "average")]
        public double? Average = null;

        [DataMember(Name = "percentile90th")]
        public double? Percentile90th = null;

        [DataMember(Name = "percentile95th")]
        public double? Percentile95th = null;

        [DataMember(Name = "percentile99th")]
        public double? Percentile99th = null;

        [DataMember(Name = "throughput")]
        public double? Throughput = null;
    }
}

Web/SummaryReports/Models/SummaryReportWrapper.cs
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Report.WebUI.Models
{

    [DataContract]
    public class SummaryReportWrapper
    {
        [DataMember(Name = "title")]
        public string Title { get; set;}

        [DataMember(Name = "summaryReportDataPoints")]
        public IEnumerable<SummaryReportDataPoint> SummaryReportDataPoints { get; set;}
    }
}

Web/SummaryReports/Controllers/FindPaymentPlanController.cs
using Hub.API.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Report.WebUI.Interfaces;
using System.Threading.Tasks;

namespace Report.WebUI.Controllers
{
    public class FindPaymentPlanController : Controller
    {
        private readonly ILogger<FindPaymentPlanController> _logger;
        private readonly ISummaryReportService _service;
        private const ApiCategory FIND_PAYMENT_PLAN_API = ApiCategory.FindPaymentPlan;

        public FindPaymentPlanController(ILogger<FindPaymentPlanController> logger, ISummaryReportService service)
        {
            _logger = logger;
            _service = service;
        }

        public async Task<IActionResult> Five_Users_Hit_To_Server_In_Duration_Of_10_Mins_Summary()
        {
            var scenario = "Find_Payment_Plan_5_Users_Hit_To_Server_In_Duration_Of_10_Mins";

            var datapoint = await _service.GetSummaryReportDataPoints(scenario, 5, FIND_PAYMENT_PLAN_API);
            ViewBag.datapoint = JsonConvert.SerializeObject(datapoint);
            return View("~/Views/Home/Report.cshtml");
        }

        public async Task<IActionResult> A_Hundred_Users_Hit_To_Server_Ramp_Up_Ramp_Down_To_25_Users_Summary()
        {
            var scenario = "Find_Payment_Plan_100_Users_Hit_To_Server_Ramp_Up_Ramp_Down_To_25_Users";

            var datapoint = await _service.GetSummaryReportDataPoints(scenario, 5, FIND_PAYMENT_PLAN_API);
            ViewBag.datapoint = JsonConvert.SerializeObject(datapoint);
            return View("~/Views/Home/Report.cshtml");
        }

    }
}

Web/SummaryReports/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Report.WebUI.Interfaces;
using Report.WebUI.Models;
using System.Diagnostics;
using System.Threading.Tasks;

namespace Report.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ISummaryReportService _service;

        public HomeController(ILogger<HomeController> logger, ISummaryReportService service)
        {
            _logger = logger;
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Versions = await _service.GetVersions();
            return View();
        }

        public IActionResult Settings(string version,string reportSetting)
        {
            SharedSettings.Version = version;
            SharedSettings.Setting = reportSetting;
            return RedirectToAction("Index");
        }

        public IActionResult ResetSettings()
        {
            SharedSettings.Version = null;
            SharedSettings.Setting = null;
            return RedirectToAction("Index");
        }

        public IActionResult Report()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/SummaryReports/Controllers/UnpaidBillsController.cs
using Hub.API.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Report.WebUI.Interfaces;
using System.Threading.Tasks;

namespace Report.WebUI.Controllers
{
    public class UnpaidBillsController : Controller
    {
        private readonly ILogger<UnpaidBillsController> _logger;
        private readonly ISummaryReportService _service;
        private const ApiCategory UNPAID_BILLS_API = ApiCategory.UnpaidBills;

        public UnpaidBillsController(ILogger<UnpaidBillsController> logger, ISummaryReportService service)
        {
            _logger = logger;
            _service = service;
        }
        public async Task<IActionResult> Five_Users_Hit_To_Server_In_Duration_Of_10_Mins_Summary()
        {
            var scenario = "Unpaid_Bills_5_Users_Hit_To_Server_In_Duration_Of_10_Mins";

            var datapoint = await _service.GetSummaryReportDataPoints(scenario, 5, UNPAID_BILLS_API);
            ViewBag.datapoint = JsonConvert.SerializeObject(datapoint);
            return View("~/Views/Home/Report.cshtml");
        }

        public async Task<IActionResult> A_Hundred_Users_Hit_To_Server_Ramp_Up_Ramp_Down_To_25_Users_Summary()
        {
            var scenario = "Unpaid_Bills_100_Users_Hit_To_Server_Ramp_Up_Ramp_Down_To_25_Users";

            var datapoint = await _service.GetSummaryReportDataPoints(scenario, 5, UNPAID_BILLS_API);
            ViewBag.datapoint = JsonConvert.SerializeObject(datapoint);
            return View("~/Views/Home/Report.cshtml");
        }
    }
}

Web/SummaryReports/Views/Home/Index.cshtml
<html>
<body>
    @{
        if (!SharedSettings.IsPresent)
        {
            <form action="Home/Settings" method="post" name="settingForm">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="reportSetting" id="radioReportSetting1" value="ByTimelines">
                    <label class="form-check-label" for="radioReportSetting1">
                        Get Top 5 Report by timelines
                    </label>
                </div>
                <br />
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="reportSetting" id="radioReportSetting2" value="ByVersion">
                    <label class="form-check-label" for="radioReportSetting2">
                        Get Top 5 Report by version
                    </label>
                </div>
                <br />
                <select class="form-control" id="version" name="version">
                    @foreach (var version in ViewBag.Versions)
                    {
                        <option>@version</option>
                    }
                </select>
                <br />
                <input type="submit" name="submit" />
            </form>
        }
        else
        {
            <form action="Home/ResetSettings" method="post" name="resetSettingForm">
                @if (SharedSettings.Setting == SharedSettings.ByTimeline)
                {
                <p>Your current report is now comparing by timelines</p>
                }
                else
                {
                <p>Your current report is now comparing by version named: @SharedSettings.Version</p>
                }

                <input type="submit" name="submit" value="Reset settings"/>
            </form>
        }
    }
</body>
</html>
<script>
    $('select[name=version]').hide();
    $('input[type=radio][name=reportSetting]').change(function () {
        if (this.value == 'ByVersion') {
            $('select[name=version]').show();
        } else {
            $('select[name=version]').hide();
        }
    });
</script>

Web/SummaryReports/Views/Home/Report.cshtml
<html>
<head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', { 'packages': ['line', 'bar', 'corechart'] });
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {

            var data = JSON.parse('@Html.Raw(ViewBag.datapoint)');

            var percentileData = new google.visualization.DataTable();
            percentileData.addColumn('string', '');
            percentileData.addColumn('number', '90th Percentile');
            percentileData.addColumn('number', '95th Percentile');
            percentileData.addColumn('number', '99th Percentile');

            var throughputData = new google.visualization.DataTable();
            throughputData.addColumn('string', '');
            throughputData.addColumn('number', 'Thoughput');

            var comboData = new google.visualization.DataTable();
            comboData.addColumn('string', '');
            comboData.addColumn('number', 'Samples');
            comboData.addColumn('number', 'Failed cases');
            comboData.addColumn('number', 'Average');

            $.each(data.summaryReportDataPoints, function (index, row) {
                percentileData.addRow([
                    row.version,
                    row.percentile90th,
                    row.percentile95th,
                    row.percentile99th,
                ]);


                throughputData.addRow([
                    row.version,
                    row.throughput,
                ]);

                comboData.addRow([
                    row.version,
                    row.samples,
                    row.failCases,
                    row.average,
                ]);

            });

            var textStyle = {
                color: 'grey',
                fontName: 'Times-Roman',
                fontSize: 13,
                bold: true,
                italic: false
            };

            var percentileOptions = {
                chart: {
                    title: 'Percentile Summary',
                },
                width: 900,
                height: 500,
                vAxis: {
                    title: 'Response time in ms',
                    format: 'decimal',
                    textStyle: textStyle
                },
                hAxis: {
                    textStyle: textStyle
                }
            };

            var throughputOptions = {
                chart: {
                    title: 'Throughput Summary',
                },
                width: 900,
                height: 500,
                vAxis: {
                    title: 'Number of transactions/sec',
                    format: 'decimal',
                    textStyle: textStyle
                },
                hAxis: {
                    textStyle: textStyle
                }
            };

            var comboOptions = {
                title: 'Overall Summary ' + data.title,
                titleTextStyle: {
                    color: '#FF0000',
                    fontSize: 20
                },
                width: 900,
                height: 500,
                vAxis: {
                    title: 'Average response time in ms',
                    format: 'decimal',
                    textStyle: textStyle
                },
                hAxis: {
                    textStyle: textStyle
                },
                seriesType: 'bars',
                series: { 2: { type: 'line' } },
            }

            var percentileChart = new google.charts.Line(document.getElementById('percentile_chart'));
            var throughputChart = new google.charts.Line(document.getElementById('throughput_chart'));
            var comboChart = new google.visualization.ComboChart(document.getElementById('combochart_chart'));
            percentileChart.draw(percentileData, google.charts.Line.convertOptions(percentileOptions));
            throughputChart.draw(throughputData, google.charts.Line.convertOptions(throughputOptions));
            comboChart.draw(comboData, comboOptions);
        }
    </script>
</head>

<body>
    <div id="combochart_chart" style="width: 1200px; height: 500px"></div>
    <br />
    <div id="throughput_chart" style="width: 1200px; height: 500px"></div>
    <br />
    <div id="percentile_chart" style="width: 1200px; height: 500px"></div>
</body>

</html>

Web/SummaryReports/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SummaryReports</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SummaryReports</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @{if (SharedSettings.IsPresent)
                    {
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item dropdown">
                                    <a href="#" id="menu" data-bs-toggle="dropdown" class="nav-link dropdown-toggle" data-bs-display="static">FUSE Based API</a>
                                    <ul class="dropdown-menu">
                                        <li class="dropdown-submenu dropright">
                                            <a href="#" data-bs-toggle="dropdown" class="dropdown-item dropdown-toggle">Find Payment Plan</a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a class="dropdown-item" asp-controller="FindPaymentPlan" asp-action="Five_Users_Hit_To_Server_In_Duration_Of_10_Mins_Summary">5 Users hit to server in 10mins</a>
                                                </li>
                                                <li>
                                                    <a class="dropdown-item" asp-controller="FindPaymentPlan" asp-action="A_Hundred_Users_Hit_To_Server_Ramp_Up_Ramp_Down_To_25_Users_Summary">100 Users hit to server then ramp-up and down by 25 users</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="dropdown-submenu dropright">
                                            <a href="#" data-bs-toggle="dropdown" class="dropdown-item dropdown-toggle">Unpaid Bills</a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a class="dropdown-item" asp-controller="UnpaidBills" asp-action="Five_Users_Hit_To_Server_In_Duration_Of_10_Mins_Summary">5 Users hit to server in 10mins</a>
                                                </li>
                                                <li>
                                                    <a class="dropdown-item" asp-controller="UnpaidBills" asp-action="A_Hundred_Users_Hit_To_Server_Ramp_Up_Ramp_Down_To_25_Users_Summary">100 Users hit to server then ramp-up and down by 25 users</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="dropdown-submenu dropright">
                                            <a href="#" data-bs-toggle="dropdown" class="dropdown-item dropdown-toggle">Get Domestic Customer</a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="#" class="dropdown-item">Item a</a>
                                                </li>
                                                <li>
                                                    <a href="#" class="dropdown-item">Item b</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="dropdown-submenu dropright">
                                            <a href="#" data-bs-toggle="dropdown" class="dropdown-item dropdown-toggle">Get Commercial Customer</a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="#" class="dropdown-item">Item a</a>
                                                </li>
                                                <li>
                                                    <a href="#" class="dropdown-item">Item b</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="dropdown-submenu dropright">
                                            <a href="#" data-bs-toggle="dropdown" class="dropdown-item dropdown-toggle">Sign Up API</a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="#" class="dropdown-item">Item a</a>
                                                </li>
                                                <li>
                                                    <a href="#" class="dropdown-item">Item b</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="dropdown-submenu dropright">
                                            <a href="#" data-bs-toggle="dropdown" class="dropdown-item dropdown-toggle">Dependent Domain</a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="#" class="dropdown-item">Item a</a>
                                                </li>
                                                <li>
                                                    <a href="#" class="dropdown-item">Item b</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="dropdown-submenu dropright">
                                            <a href="#" data-bs-toggle="dropdown" class="dropdown-item dropdown-toggle">Simple Domain</a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="#" class="dropdown-item">Item a</a>
                                                </li>
                                                <li>
                                                    <a href="#" class="dropdown-item">Item b</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="dropdown-submenu dropright">
                                            <a href="#" data-bs-toggle="dropdown" class="dropdown-item dropdown-toggle">Get Offers</a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="#" class="dropdown-item">Item a</a>
                                                </li>
                                                <li>
                                                    <a href="#" class="dropdown-item">Item b</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>

                                <li class="nav-item dropdown">
                                    <a href="#" id="menu" data-bs-toggle="dropdown" class="nav-link dropdown-toggle" data-bs-display="static">HCM API</a>
                                    <ul class="dropdown-menu">
                                        <li class="dropdown-submenu dropright">
                                            <a href="#" data-bs-toggle="dropdown" class="dropdown-item dropdown-toggle">Get Usage</a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a class="dropdown-item" asp-controller="FindPaymentPlan" asp-action="Five_Users_Hit_To_Server_In_Duration_Of_10_Mins_Summary">5 Users hit to server in 10mins</a>
                                                </li>
                                                <li>
                                                    <a class="dropdown-item" asp-controller="FindPaymentPlan" asp-action="A_Hundred_Users_Hit_To_Server_Ramp_Up_Ramp_Down_To_25_Users_Summary">100 Users hit to server then ramp-up and down by 25 users</a>

                                                </li>
                                            </ul>
                                        </li>
                                        <li class="dropdown-submenu dropright">
                                            <a href="#" data-bs-toggle="dropdown" class="dropdown-item dropdown-toggle">Get Usage Detail</a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="#" class="dropdown-item">Item a</a>
                                                </li>
                                                <li>
                                                    <a href="#" class="dropdown-item">Item b</a>
                                                </li>
                                            </ul>
                                        </li>

                                        <li class="dropdown-submenu dropright">
                                            <a href="#" data-bs-toggle="dropdown" class="dropdown-item dropdown-toggle">Get Invoice</a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="#" class="dropdown-item">Item a</a>
                                                </li>
                                                <li>
                                                    <a href="#" class="dropdown-item">Item b</a>
                                                </li>
                                            </ul>
                                        </li>

                                        <li class="dropdown-submenu dropright">
                                            <a href="#" data-bs-toggle="dropdown" class="dropdown-item dropdown-toggle">Get Customer</a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="#" class="dropdown-item">Item a</a>
                                                </li>
                                                <li>
                                                    <a href="#" class="dropdown-item">Item b</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    }
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SummaryReports
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

<style>
    .dropdown-submenu {
        position: relative;
    }

        .dropdown-submenu .dropdown-menu {
            top: 0;
            left: 100%;
            margin-top: -1px;
        }

    .navbar-nav li:hover > ul.dropdown-menu {
        display: block;
    }
</style>